In [25]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35], 
    'City': ['NYC', 'LA', 'Chicago']
}
df = pd.DataFrame(data)

In [26]:
display(df)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago

In [27]:
data = [['Melissa', 29, 'Detroit'],
        ['Joe', 30, 'San Fran'],
        ['Mildred', 35, 'Atlanta']]
df = pd.DataFrame(data, 
    columns=['Name', 'Years', 'Location'])

In [28]:
display(df)

      Name  Years  Location
0  Melissa     29   Detroit
1      Joe     30  San Fran
2  Mildred     35   Atlanta

In [29]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35], 
    'City': ['NYC', 'LA', 'Chicago']
}
df = pd.DataFrame(data)

In [30]:
display(df)

# Boolean indexing
young_people = df[df['Age'] < 30]
display(young_people)

# Multiple conditions
ny_young = df[(df['Age'] < 30) & 
              (df['City'] == 'NYC')]
display(ny_young)
    
# Using query method
result = df.query('Age > 25 and City == "LA"')
display(result)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago

    Name  Age City
0  Alice   25  NYC

    Name  Age City
0  Alice   25  NYC

  Name  Age City
1  Bob   30   LA

In [31]:
# Group by city
city_groups = df.groupby('City')

# Aggregate functions
avg_age_by_city = city_groups['Age'].mean()
display(avg_age_by_city)

# Multiple aggregations
stats = city_groups.agg({
    'Age': ['mean', 'max', 'min']
})
display(stats)

City
Chicago    35.0
LA         30.0
NYC        25.0
Name: Age, dtype: float64

          Age
         mean max min
City
Chicago  35.0  35  35
LA       30.0  30  30
NYC      25.0  25  25

In [32]:
# Sort by values
sorted_df = df.sort_values('Age', 
                          ascending=False)
display(sorted_df)

# Sort by multiple columns
multi_sort = df.sort_values(['City', 'Age'])
display(multi_sort)

# Rank values
df['Age_Rank'] = df['Age'].rank()
display(df)

sorted_df['Age_Rank'] = sorted_df['Age'].rank()
display(sorted_df)

      Name  Age     City
2  Charlie   35  Chicago
1      Bob   30       LA
0    Alice   25      NYC

      Name  Age     City
2  Charlie   35  Chicago
1      Bob   30       LA
0    Alice   25      NYC

      Name  Age     City  Age_Rank
0    Alice   25      NYC       1.0
1      Bob   30       LA       2.0
2  Charlie   35  Chicago       3.0

      Name  Age     City  Age_Rank
2  Charlie   35  Chicago       3.0
1      Bob   30       LA       2.0
0    Alice   25      NYC       1.0