# Demo: Comparing `.loc[]` and `.iloc[]` in Pandas

In [1]:
# Step 1: Import libraries
import pandas as pd

# Step 2: Create a simple DataFrame
df = pd.DataFrame({
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Population': [8419600, 3980400, 2716000, 2328000, 1690000],
    'Region': ['East', 'West', 'Midwest', 'South', 'West']
}, index=['NY', 'LA', 'CH', 'HO', 'PH'])

# Display the DataFrame
print("=== Original DataFrame ===")
display(df)

=== Original DataFrame ===

           City  Population   Region
NY     New York     8419600     East
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South
PH      Phoenix     1690000     West

In [4]:
display(df)

# Select one row by label
print("Select row with index label 'CH':")
display(df.loc['CH'])

# Select multiple rows by label
print("Select rows 'NY' and 'HO':")
display(df.loc[['NY', 'HO']])

# Select a range of rows by label (note: inclusive!)
print("Select rows from 'LA' to 'HO':")
display(df.loc['LA':'HO'])

           City  Population   Region
NY     New York     8419600     East
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South
PH      Phoenix     1690000     West

Select row with index label 'CH':

City          Chicago
Population    2716000
Region        Midwest
Name: CH, dtype: object

Select rows 'NY' and 'HO':

        City  Population Region
NY  New York     8419600   East
HO   Houston     2328000  South

Select rows from 'LA' to 'HO':

           City  Population   Region
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South

In [5]:
display(df)

# Select one row by integer position
print("Select the first row (position 0):")
display(df.iloc[0])

# Select multiple rows by position
print("Select rows at positions 1 and 3:")
display(df.iloc[[1, 3]])

# Select a range of rows by position (note: exclusive!)
print("Select rows at positions 1 through 3:")
display(df.iloc[1:3])

           City  Population   Region
NY     New York     8419600     East
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South
PH      Phoenix     1690000     West

Select the first row (position 0):

City          New York
Population     8419600
Region            East
Name: NY, dtype: object

Select rows at positions 1 and 3:

           City  Population Region
LA  Los Angeles     3980400   West
HO      Houston     2328000  South

Select rows at positions 1 through 3:

           City  Population   Region
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest

**NOTE**: `.iloc[1:3]` includes rows 1 and 2, but not 3 (different from label-based selection using `loc[]`)

### Selecting Rows and Columns

In [6]:
display(df)

# loc: uses row & column labels
print("Using .loc: select rows 'NY' to 'CH' and columns 'City' & 'Population'")
display(df.loc['NY':'CH', ['City', 'Population']])

# iloc: uses integer positions
print("Using .iloc: select first 3 rows and first 2 columns")
display(df.iloc[0:3, 0:2])

           City  Population   Region
NY     New York     8419600     East
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South
PH      Phoenix     1690000     West

Using .loc: select rows 'NY' to 'CH' and columns 'City' & 'Population'

           City  Population
NY     New York     8419600
LA  Los Angeles     3980400
CH      Chicago     2716000

Using .iloc: select first 3 rows and first 2 columns

           City  Population
NY     New York     8419600
LA  Los Angeles     3980400
CH      Chicago     2716000

### Boolean Filtering with `loc[]`

In [7]:
display(df)

# Boolean condition: cities with population > 3 million
print("Cities with population > 3 million (using loc):")
display(df.loc[df['Population'] > 3_000_000])

           City  Population   Region
NY     New York     8419600     East
LA  Los Angeles     3980400     West
CH      Chicago     2716000  Midwest
HO      Houston     2328000    South
PH      Phoenix     1690000     West

Cities with population > 3 million (using loc):

           City  Population Region
NY     New York     8419600   East
LA  Los Angeles     3980400   West

| Feature                   | `.loc[]`    | `.iloc[]`              |
| ------------------------- | ----------- | ---------------------- |
| Indexing type             | Label-based | Integer position-based |
| End value in slice        | Inclusive   | Exclusive              |
| Boolean masking           | ✅ Supported | ✅ Supported            |
| Accepts integer positions | ❌           | ✅                      |
| Accepts labels            | ✅           | ❌                      |